### ISSUE TITLE
Incorrect location of lamps

### ISSUE THREAD

**Issue by Dez1gner** [semagnum/light-painter#29]
![MMDF0AF](https://user-images.githubusercontent.com/38717527/233766756-54ad9bb2-7164-40df-bccb-b24c82255648.png)

For some reason, the lamp is not placed where it should be. On the other side, well...

**Comment by semagnum** [comment]
Is your stroke placement on the surface, or on the 3D cursor plane?

![image](https://user-images.githubusercontent.com/46832095/233781590-7cd4cdad-acfb-4e6a-98fb-5d4bdb922008.png)

**Comment by Dez1gner** [comment]
Thank you.
Yes, there was a 3D Cursor mode and this led to an error. I put it on Surface and now everything is correct.

**Comment by semagnum** [comment]
Thank you for the update! I appreciate it. I'd recommend looking through the [docs](https://semagnum.github.io/light-painter/) if you have questions. I did mention there that both 3D cursor and surface as a recommended placement method. 3D cursor can be useful if you're doing anything other than the surface normal axis, but otherwise I recommend just sticking to just "Surface".

Closing as issue has been resolved.
