### ISSUE TITLE
Adjust existing light position

### ISSUE THREAD

**Issue by kalamazandy** [semagnum/light-painter#39]
I used 3dsMax a while ago and they had a tool to set a highlight. This is a step beyond that because you're adding things like scale and rotation to area lights to attempt to add the highlight right where you want it. So thank you. I was missing the feature from Max and this is even More useful.

It would be great to be able to store the paint lamp settings with the light object (maybe as custom properties?) so the user could select the light and draw for a new location. 
And it may be a bit more complicated, but one nice thing about the Max method was it was a click-and-drag real-time update. For repositioning only, that could be a nice feature. And I would add one feature to that as well. Click and drag is nice, but for area lights, rotation also matters, so it would be cool to hold a key to rotate the light. Let go and continue positioning. Something like that.

Being able to change existing lights also allows to use the tool to animate from one position to another, rather than creating one light, then creating another light, copying it's information down, then changing your light to those settings.

**Comment by semagnum** [comment]
An adjust tool for lamps is a great idea. Added to the backlog.

That's a cool idea to choose whether the tool only adjusts the position and not rotation. My initial idea would be that the tool would just check the active lamp's type: if an area or spot lamp, rotation matters; for point lamps, it doesn't matter. But you're saying that even then, it should be optional?

**Comment by semagnum** [comment]
For those who don't know, Blender has a ~~very basic~~ implementation of this built in: when a light is actively selected, there's a little yellow dot that's a gizmo you can drag around to adjust the rotation to light a surface normal. But if you hold down Ctrl, it also positions the lamp.

![Blender screenshot of dragging a light's yellow gizmo, holding down Ctrl to adjust position as well](https://github.com/semagnum/light-painter/assets/46832095/c6cf0e06-5519-47ba-87c6-3d3c9a660b8d)

I know this doesn't match what you're asking, I'll still add this to my backlog 🙂 but just for awareness because I didn't even know until someone mentioned it on my BlenderArtists post.

**Comment by semagnum** [comment]
Feature added in https://github.com/semagnum/light-painter/releases/tag/1.0.3, closing.
