### ISSUE TITLE
Lamp Adjust - weird power value behavior, lamp shape always starts as a rectangle

### ISSUE THREAD

**Issue by chenpaner** [semagnum/light-painter#45]
1，Power cannot be adjusted to more than 10.
![Snipaste_2023-11-21_20-08-20](https://github.com/semagnum/light-painter/assets/107256886/bf6fee6b-955f-4b1c-ad22-318a523d0b19)

2，When I use Adjusting Lights, the Disk Lights will be automatically changed to RECTANGLE. Can you add an automatic recognition without modifying the default type?

**Comment by semagnum** [comment]
For the first issue, looks like the `POWER` subtype and unit option for the `power` parameter is messing with its precision? It also happens when adding lights. If I remove those options, the issue is gone. Yet the subtype and unit options are what allow it to be read as "180 **W**" instead of just 180. I'll try some research - if I can't find a workaround keeping the units, I may just take it off.

The second issue is an easy fix - honestly surprised I didn't have it take defaults sooner. Again, appreciate it.

**Comment by semagnum** [comment]
Looks like the power issue is an open Blender issue: https://projects.blender.org/blender/blender/issues/77791

I may have to remove the subtype and unit for now :/
